export { default as api } from './api';
export { authApi, adminApi } from './authApi';
export { doctorApi } from './doctorApi';
export { consultationApi } from './consultationApi';
export { paymentApi } from './paymentApi';
export { dependentApi } from './dependentApi';
export { doctorPanelApi } from './doctorPanelApi';
export { appointmentApi } from './appointmentApi';
export { chatApi } from './chatApi';
export { medicalRecordApi } from './medicalRecordApi';
export { videoRoomApi } from './videoRoomApi';
